from pydantic import BaseModel, Field
from datetime import datetime
from typing import List

# 1. UPDATED: Expects the encrypted AES-GCM string, NOT the plaintext password
class EvaluatorShareCreate(BaseModel):
    name: str = Field(..., max_length=100)
    # The AES encrypted share is a long string, so we cap it at 1000 to be safe
    encrypted_share: str = Field(..., max_length=1000)

# 2. UPDATED: Includes the new master public keys generated by the Vault
class AuctionCreate(BaseModel):
    title: str = Field(..., max_length=200)
    description: str = Field(..., max_length=1000)
    deadline: datetime
    master_pub_x: str = Field(..., max_length=100)
    master_pub_y: str = Field(..., max_length=100)
    # DOS DEFENSE: Prevent an attacker from creating an auction with 100,000 evaluators
    evaluators: List[EvaluatorShareCreate] = Field(..., min_length=5, max_length=5)

class AuctionResponse(BaseModel):
    id: int
    title: str
    description: str
    deadline: datetime
    master_pub_x: str
    master_pub_y: str

class BidSubmit(BaseModel):
    auction_id: int = Field(..., gt=0)
    # A SHA-256 hash is ALWAYS exactly 64 characters. Reject anything else immediately.
    bidder_hash: str = Field(..., min_length=64, max_length=64)
    signature: str = Field(..., max_length=1000)
    
    # Cap ECC Coordinates to 100 chars to block massive string injections
    id_c1_x: str = Field(..., max_length=100)
    id_c1_y: str = Field(..., max_length=100)
    id_c2_x: str = Field(..., max_length=100)
    id_c2_y: str = Field(..., max_length=100)
    encrypted_c1_x: str = Field(..., max_length=100)
    encrypted_c1_y: str = Field(..., max_length=100)
    encrypted_c2_x: str = Field(..., max_length=100)
    encrypted_c2_y: str = Field(..., max_length=100)

class DecryptRequest(BaseModel):
    shares: List[str]
    passwords: List[str]